### ISSUE TITLE
Thinner CheapRuler

### ISSUE THREAD

**Issue by alexkirsz** [vipera/cheap-ruler-rs#5]
Hello!

As mentioned in the README:
> This Rust port additionally allows the distance unit of the ruler to be changed and retrieved at any point after construction at the cost of larger memory size of the ruler struct itself (40 bytes instead of 16 bytes), but with no additional overhead.

Would it be possible to either:
* expose a version of `CheapRuler` that doesn't allow for this, and weighs 16 bytes; or
* add a feature to disable this.

My use case doesn't need changing the distance unit, so it would be great to have the option of smaller structs.

**Comment by vipera** [comment]
Hi!

I've actually considered this point myself and have come to believe it was a poor tradeoff to make. In fact, I've never used any distance unit except meters—any of the other units are simply a single multiplication away anyway.

I would be interested in completely removing `change_unit`, `clone_with_unit` and `distance_unit` and dropping extraneous fields from the struct instead of toggling their inclusion via a feature flag, as I just don't see any utility in keeping them. It would mean a major version change, but I would be surprised if it required any dependent projects to work around the change.

**Comment by vipera** [comment]
I've implemented the change in 781ec54, released as v0.4.0. If you didn't use any of the distance methods, upgrading should be easy for you. Enjoy a thinner cheap ruler!

**Comment by alexkirsz** [comment]
Thanks for the quick turnaround on this issue, much appreciated!
